#!/bin/bash
printf "%o\n" $(( $((5#$(echo $WATER | tr water 01234))) + $((5#$(echo $STIR | tr stir. 01234))) )) |tr 01234567 bestchol \


# Convert WATER to base 5 number
w=$(echo "$WATER" | tr 'water' '01234')

# Convert STIR to base 5 number
s=$(echo "$STIR" | tr 'stir.' '01234')

# Add the two base 5 numbers (converted to decimal)
sum=$((5#$w + 5#$s))

# Convert the sum to octal (base 8)
octal=$(printf "%o" "$sum")

# Translate octal digits to base bestchol
echo "$octal" | tr '01234567' 'bestchol'
